// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/pb_msg/ai_bone.proto

#include "common/pb_msg/ai_bone.pb.h"

#include <algorithm>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
#include "google/protobuf/generated_message_tctable_impl.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
namespace pb_msg {
        template <typename>
PROTOBUF_CONSTEXPR AiBone::AiBone(::_pbi::ConstantInitialized)
    : _impl_{
      /*decltype(_impl_._has_bits_)*/ {},
      /*decltype(_impl_._cached_size_)*/ {},
      /*decltype(_impl_.armature_)*/ {},
      /*decltype(_impl_.node_)*/ {},
      /*decltype(_impl_.weights_)*/ {},
      /*decltype(_impl_.name_)*/ {
          &::_pbi::fixed_address_empty_string,
          ::_pbi::ConstantInitialized{},
      },
      /*decltype(_impl_.offsetmatrix_)*/ nullptr,
      /*decltype(_impl_.numweights_)*/ 0u,
    } {}
struct AiBoneDefaultTypeInternal {
  PROTOBUF_CONSTEXPR AiBoneDefaultTypeInternal() : _instance(::_pbi::ConstantInitialized{}) {}
  ~AiBoneDefaultTypeInternal() {}
  union {
    AiBone _instance;
  };
};

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 AiBoneDefaultTypeInternal _AiBone_default_instance_;
}  // namespace pb_msg
static ::_pb::Metadata file_level_metadata_common_2fpb_5fmsg_2fai_5fbone_2eproto[1];
static constexpr const ::_pb::EnumDescriptor**
    file_level_enum_descriptors_common_2fpb_5fmsg_2fai_5fbone_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor**
    file_level_service_descriptors_common_2fpb_5fmsg_2fai_5fbone_2eproto = nullptr;
const ::uint32_t TableStruct_common_2fpb_5fmsg_2fai_5fbone_2eproto::offsets[] PROTOBUF_SECTION_VARIABLE(
    protodesc_cold) = {
    PROTOBUF_FIELD_OFFSET(::pb_msg::AiBone, _impl_._has_bits_),
    PROTOBUF_FIELD_OFFSET(::pb_msg::AiBone, _internal_metadata_),
    ~0u,  // no _extensions_
    ~0u,  // no _oneof_case_
    ~0u,  // no _weak_field_map_
    ~0u,  // no _inlined_string_donated_
    ~0u,  // no _split_
    ~0u,  // no sizeof(Split)
    PROTOBUF_FIELD_OFFSET(::pb_msg::AiBone, _impl_.name_),
    PROTOBUF_FIELD_OFFSET(::pb_msg::AiBone, _impl_.numweights_),
    PROTOBUF_FIELD_OFFSET(::pb_msg::AiBone, _impl_.armature_),
    PROTOBUF_FIELD_OFFSET(::pb_msg::AiBone, _impl_.node_),
    PROTOBUF_FIELD_OFFSET(::pb_msg::AiBone, _impl_.weights_),
    PROTOBUF_FIELD_OFFSET(::pb_msg::AiBone, _impl_.offsetmatrix_),
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    ~0u,
    0,
};

static const ::_pbi::MigrationSchema
    schemas[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
        {0, 14, -1, sizeof(::pb_msg::AiBone)},
};

static const ::_pb::Message* const file_default_instances[] = {
    &::pb_msg::_AiBone_default_instance_._instance,
};
const char descriptor_table_protodef_common_2fpb_5fmsg_2fai_5fbone_2eproto[] PROTOBUF_SECTION_VARIABLE(protodesc_cold) = {
    "\n\033common/pb_msg/ai_bone.proto\022\006pb_msg\032\032c"
    "ommon/pb_msg/common.proto\032$common/pb_msg"
    "/ai_vertex_weight.proto\032\033common/pb_msg/a"
    "i_node.proto\"\276\001\n\006AiBone\022\014\n\004Name\030\001 \001(\t\022\022\n"
    "\nNumWeights\030\002 \001(\r\022 \n\010Armature\030\003 \003(\0132\016.pb"
    "_msg.AiNode\022\034\n\004Node\030\004 \003(\0132\016.pb_msg.AiNod"
    "e\022\'\n\007Weights\030\005 \003(\0132\026.pb_msg.AiVertexWeig"
    "ht\022)\n\014OffsetMatrix\030\006 \001(\0132\023.pb_msg.AiMatr"
    "ix4x4B\017Z\rcommon/pb_msgb\006proto3"
};
static const ::_pbi::DescriptorTable* const descriptor_table_common_2fpb_5fmsg_2fai_5fbone_2eproto_deps[3] =
    {
        &::descriptor_table_common_2fpb_5fmsg_2fai_5fnode_2eproto,
        &::descriptor_table_common_2fpb_5fmsg_2fai_5fvertex_5fweight_2eproto,
        &::descriptor_table_common_2fpb_5fmsg_2fcommon_2eproto,
};
static ::absl::once_flag descriptor_table_common_2fpb_5fmsg_2fai_5fbone_2eproto_once;
const ::_pbi::DescriptorTable descriptor_table_common_2fpb_5fmsg_2fai_5fbone_2eproto = {
    false,
    false,
    350,
    descriptor_table_protodef_common_2fpb_5fmsg_2fai_5fbone_2eproto,
    "common/pb_msg/ai_bone.proto",
    &descriptor_table_common_2fpb_5fmsg_2fai_5fbone_2eproto_once,
    descriptor_table_common_2fpb_5fmsg_2fai_5fbone_2eproto_deps,
    3,
    1,
    schemas,
    file_default_instances,
    TableStruct_common_2fpb_5fmsg_2fai_5fbone_2eproto::offsets,
    file_level_metadata_common_2fpb_5fmsg_2fai_5fbone_2eproto,
    file_level_enum_descriptors_common_2fpb_5fmsg_2fai_5fbone_2eproto,
    file_level_service_descriptors_common_2fpb_5fmsg_2fai_5fbone_2eproto,
};

// This function exists to be marked as weak.
// It can significantly speed up compilation by breaking up LLVM's SCC
// in the .pb.cc translation units. Large translation units see a
// reduction of more than 35% of walltime for optimized builds. Without
// the weak attribute all the messages in the file, including all the
// vtables and everything they use become part of the same SCC through
// a cycle like:
// GetMetadata -> descriptor table -> default instances ->
//   vtables -> GetMetadata
// By adding a weak function here we break the connection from the
// individual vtables back into the descriptor table.
PROTOBUF_ATTRIBUTE_WEAK const ::_pbi::DescriptorTable* descriptor_table_common_2fpb_5fmsg_2fai_5fbone_2eproto_getter() {
  return &descriptor_table_common_2fpb_5fmsg_2fai_5fbone_2eproto;
}
// Force running AddDescriptors() at dynamic initialization time.
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2
static ::_pbi::AddDescriptorsRunner dynamic_init_dummy_common_2fpb_5fmsg_2fai_5fbone_2eproto(&descriptor_table_common_2fpb_5fmsg_2fai_5fbone_2eproto);
namespace pb_msg {
// ===================================================================

class AiBone::_Internal {
 public:
  using HasBits = decltype(std::declval<AiBone>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
    8 * PROTOBUF_FIELD_OFFSET(AiBone, _impl_._has_bits_);
  static const ::pb_msg::AiMatrix4x4& offsetmatrix(const AiBone* msg);
  static void set_has_offsetmatrix(HasBits* has_bits) {
    (*has_bits)[0] |= 1u;
  }
};

const ::pb_msg::AiMatrix4x4& AiBone::_Internal::offsetmatrix(const AiBone* msg) {
  return *msg->_impl_.offsetmatrix_;
}
void AiBone::clear_armature() {
  _internal_mutable_armature()->Clear();
}
void AiBone::clear_node() {
  _internal_mutable_node()->Clear();
}
void AiBone::clear_weights() {
  _internal_mutable_weights()->Clear();
}
void AiBone::clear_offsetmatrix() {
  if (_impl_.offsetmatrix_ != nullptr) _impl_.offsetmatrix_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
AiBone::AiBone(::google::protobuf::Arena* arena)
    : ::google::protobuf::Message(arena) {
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:pb_msg.AiBone)
}
AiBone::AiBone(const AiBone& from) : ::google::protobuf::Message() {
  AiBone* const _this = this;
  (void)_this;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){from._impl_._has_bits_},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.armature_){from._impl_.armature_},
      decltype(_impl_.node_){from._impl_.node_},
      decltype(_impl_.weights_){from._impl_.weights_},
      decltype(_impl_.name_){},
      decltype(_impl_.offsetmatrix_){nullptr},
      decltype(_impl_.numweights_){},
  };
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.name_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (!from._internal_name().empty()) {
    _this->_impl_.name_.Set(from._internal_name(), _this->GetArenaForAllocation());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_impl_.offsetmatrix_ = new ::pb_msg::AiMatrix4x4(*from._impl_.offsetmatrix_);
  }
  _this->_impl_.numweights_ = from._impl_.numweights_;

  // @@protoc_insertion_point(copy_constructor:pb_msg.AiBone)
}
inline void AiBone::SharedCtor(::_pb::Arena* arena) {
  (void)arena;
  new (&_impl_) Impl_{
      decltype(_impl_._has_bits_){},
      /*decltype(_impl_._cached_size_)*/ {},
      decltype(_impl_.armature_){arena},
      decltype(_impl_.node_){arena},
      decltype(_impl_.weights_){arena},
      decltype(_impl_.name_){},
      decltype(_impl_.offsetmatrix_){nullptr},
      decltype(_impl_.numweights_){0u},
  };
  _impl_.name_.InitDefault();
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        _impl_.name_.Set("", GetArenaForAllocation());
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
}
AiBone::~AiBone() {
  // @@protoc_insertion_point(destructor:pb_msg.AiBone)
  _internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  SharedDtor();
}
inline void AiBone::SharedDtor() {
  ABSL_DCHECK(GetArenaForAllocation() == nullptr);
  _impl_.armature_.~RepeatedPtrField();
  _impl_.node_.~RepeatedPtrField();
  _impl_.weights_.~RepeatedPtrField();
  _impl_.name_.Destroy();
  if (this != internal_default_instance()) delete _impl_.offsetmatrix_;
}
void AiBone::SetCachedSize(int size) const {
  _impl_._cached_size_.Set(size);
}

PROTOBUF_NOINLINE void AiBone::Clear() {
// @@protoc_insertion_point(message_clear_start:pb_msg.AiBone)
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  _internal_mutable_armature()->Clear();
  _internal_mutable_node()->Clear();
  _internal_mutable_weights()->Clear();
  _impl_.name_.ClearToEmpty();
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    ABSL_DCHECK(_impl_.offsetmatrix_ != nullptr);
    _impl_.offsetmatrix_->Clear();
  }
  _impl_.numweights_ = 0u;
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

const char* AiBone::_InternalParse(
    const char* ptr, ::_pbi::ParseContext* ctx) {
  ptr = ::_pbi::TcParser::ParseLoop(this, ptr, ctx, &_table_.header);
  return ptr;
}


PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1
const ::_pbi::TcParseTable<3, 6, 4, 26, 2> AiBone::_table_ = {
  {
    PROTOBUF_FIELD_OFFSET(AiBone, _impl_._has_bits_),
    0, // no _extensions_
    6, 56,  // max_field_number, fast_idx_mask
    offsetof(decltype(_table_), field_lookup_table),
    4294967232,  // skipmap
    offsetof(decltype(_table_), field_entries),
    6,  // num_field_entries
    4,  // num_aux_entries
    offsetof(decltype(_table_), aux_entries),
    &_AiBone_default_instance_._instance,
    ::_pbi::TcParser::GenericFallback,  // fallback
  }, {{
    {::_pbi::TcParser::MiniParse, {}},
    // string Name = 1;
    {::_pbi::TcParser::FastUS1,
     {10, 63, 0, PROTOBUF_FIELD_OFFSET(AiBone, _impl_.name_)}},
    // uint32 NumWeights = 2;
    {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(AiBone, _impl_.numweights_), 63>(),
     {16, 63, 0, PROTOBUF_FIELD_OFFSET(AiBone, _impl_.numweights_)}},
    // repeated .pb_msg.AiNode Armature = 3;
    {::_pbi::TcParser::FastMtR1,
     {26, 63, 0, PROTOBUF_FIELD_OFFSET(AiBone, _impl_.armature_)}},
    // repeated .pb_msg.AiNode Node = 4;
    {::_pbi::TcParser::FastMtR1,
     {34, 63, 1, PROTOBUF_FIELD_OFFSET(AiBone, _impl_.node_)}},
    // repeated .pb_msg.AiVertexWeight Weights = 5;
    {::_pbi::TcParser::FastMtR1,
     {42, 63, 2, PROTOBUF_FIELD_OFFSET(AiBone, _impl_.weights_)}},
    // .pb_msg.AiMatrix4x4 OffsetMatrix = 6;
    {::_pbi::TcParser::FastMtS1,
     {50, 0, 3, PROTOBUF_FIELD_OFFSET(AiBone, _impl_.offsetmatrix_)}},
    {::_pbi::TcParser::MiniParse, {}},
  }}, {{
    65535, 65535
  }}, {{
    // string Name = 1;
    {PROTOBUF_FIELD_OFFSET(AiBone, _impl_.name_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUtf8String | ::_fl::kRepAString)},
    // uint32 NumWeights = 2;
    {PROTOBUF_FIELD_OFFSET(AiBone, _impl_.numweights_), -1, 0,
    (0 | ::_fl::kFcSingular | ::_fl::kUInt32)},
    // repeated .pb_msg.AiNode Armature = 3;
    {PROTOBUF_FIELD_OFFSET(AiBone, _impl_.armature_), -1, 0,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .pb_msg.AiNode Node = 4;
    {PROTOBUF_FIELD_OFFSET(AiBone, _impl_.node_), -1, 1,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // repeated .pb_msg.AiVertexWeight Weights = 5;
    {PROTOBUF_FIELD_OFFSET(AiBone, _impl_.weights_), -1, 2,
    (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    // .pb_msg.AiMatrix4x4 OffsetMatrix = 6;
    {PROTOBUF_FIELD_OFFSET(AiBone, _impl_.offsetmatrix_), _Internal::kHasBitsOffset + 0, 3,
    (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
  }}, {{
    {::_pbi::TcParser::GetTable<::pb_msg::AiNode>()},
    {::_pbi::TcParser::GetTable<::pb_msg::AiNode>()},
    {::_pbi::TcParser::GetTable<::pb_msg::AiVertexWeight>()},
    {::_pbi::TcParser::GetTable<::pb_msg::AiMatrix4x4>()},
  }}, {{
    "\15\4\0\0\0\0\0\0"
    "pb_msg.AiBone"
    "Name"
  }},
};

::uint8_t* AiBone::_InternalSerialize(
    ::uint8_t* target,
    ::google::protobuf::io::EpsCopyOutputStream* stream) const {
  // @@protoc_insertion_point(serialize_to_array_start:pb_msg.AiBone)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  // string Name = 1;
  if (!this->_internal_name().empty()) {
    const std::string& _s = this->_internal_name();
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
        _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "pb_msg.AiBone.Name");
    target = stream->WriteStringMaybeAliased(1, _s, target);
  }

  // uint32 NumWeights = 2;
  if (this->_internal_numweights() != 0) {
    target = stream->EnsureSpace(target);
    target = ::_pbi::WireFormatLite::WriteUInt32ToArray(
        2, this->_internal_numweights(), target);
  }

  // repeated .pb_msg.AiNode Armature = 3;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_armature_size()); i < n; i++) {
    const auto& repfield = this->_internal_armature().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(3, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .pb_msg.AiNode Node = 4;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_node_size()); i < n; i++) {
    const auto& repfield = this->_internal_node().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(4, repfield, repfield.GetCachedSize(), target, stream);
  }

  // repeated .pb_msg.AiVertexWeight Weights = 5;
  for (unsigned i = 0,
      n = static_cast<unsigned>(this->_internal_weights_size()); i < n; i++) {
    const auto& repfield = this->_internal_weights().Get(i);
    target = ::google::protobuf::internal::WireFormatLite::
        InternalWriteMessage(5, repfield, repfield.GetCachedSize(), target, stream);
  }

  cached_has_bits = _impl_._has_bits_[0];
  // .pb_msg.AiMatrix4x4 OffsetMatrix = 6;
  if (cached_has_bits & 0x00000001u) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessage(6, _Internal::offsetmatrix(this),
        _Internal::offsetmatrix(this).GetCachedSize(), target, stream);
  }

  if (PROTOBUF_PREDICT_FALSE(_internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:pb_msg.AiBone)
  return target;
}

::size_t AiBone::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:pb_msg.AiBone)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  // repeated .pb_msg.AiNode Armature = 3;
  total_size += 1UL * this->_internal_armature_size();
  for (const auto& msg : this->_internal_armature()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // repeated .pb_msg.AiNode Node = 4;
  total_size += 1UL * this->_internal_node_size();
  for (const auto& msg : this->_internal_node()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // repeated .pb_msg.AiVertexWeight Weights = 5;
  total_size += 1UL * this->_internal_weights_size();
  for (const auto& msg : this->_internal_weights()) {
    total_size +=
      ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
  }
  // string Name = 1;
  if (!this->_internal_name().empty()) {
    total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                    this->_internal_name());
  }

  // .pb_msg.AiMatrix4x4 OffsetMatrix = 6;
  cached_has_bits = _impl_._has_bits_[0];
  if (cached_has_bits & 0x00000001u) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSize(
        *_impl_.offsetmatrix_);
  }

  // uint32 NumWeights = 2;
  if (this->_internal_numweights() != 0) {
    total_size += ::_pbi::WireFormatLite::UInt32SizePlusOne(
        this->_internal_numweights());
  }

  return MaybeComputeUnknownFieldsSize(total_size, &_impl_._cached_size_);
}

const ::google::protobuf::Message::ClassData AiBone::_class_data_ = {
    ::google::protobuf::Message::CopyWithSourceCheck,
    AiBone::MergeImpl
};
const ::google::protobuf::Message::ClassData*AiBone::GetClassData() const { return &_class_data_; }


void AiBone::MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg) {
  auto* const _this = static_cast<AiBone*>(&to_msg);
  auto& from = static_cast<const AiBone&>(from_msg);
  // @@protoc_insertion_point(class_specific_merge_from_start:pb_msg.AiBone)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void) cached_has_bits;

  _this->_internal_mutable_armature()->MergeFrom(from._internal_armature());
  _this->_internal_mutable_node()->MergeFrom(from._internal_node());
  _this->_internal_mutable_weights()->MergeFrom(from._internal_weights());
  if (!from._internal_name().empty()) {
    _this->_internal_set_name(from._internal_name());
  }
  if ((from._impl_._has_bits_[0] & 0x00000001u) != 0) {
    _this->_internal_mutable_offsetmatrix()->::pb_msg::AiMatrix4x4::MergeFrom(
        from._internal_offsetmatrix());
  }
  if (from._internal_numweights() != 0) {
    _this->_internal_set_numweights(from._internal_numweights());
  }
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(from._internal_metadata_);
}

void AiBone::CopyFrom(const AiBone& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:pb_msg.AiBone)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

PROTOBUF_NOINLINE bool AiBone::IsInitialized() const {
  return true;
}

void AiBone::InternalSwap(AiBone* other) {
  using std::swap;
  auto* lhs_arena = GetArenaForAllocation();
  auto* rhs_arena = other->GetArenaForAllocation();
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.armature_.InternalSwap(&other->_impl_.armature_);
  _impl_.node_.InternalSwap(&other->_impl_.node_);
  _impl_.weights_.InternalSwap(&other->_impl_.weights_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.name_, lhs_arena,
                                       &other->_impl_.name_, rhs_arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(AiBone, _impl_.numweights_)
      + sizeof(AiBone::_impl_.numweights_)
      - PROTOBUF_FIELD_OFFSET(AiBone, _impl_.offsetmatrix_)>(
          reinterpret_cast<char*>(&_impl_.offsetmatrix_),
          reinterpret_cast<char*>(&other->_impl_.offsetmatrix_));
}

::google::protobuf::Metadata AiBone::GetMetadata() const {
  return ::_pbi::AssignDescriptors(
      &descriptor_table_common_2fpb_5fmsg_2fai_5fbone_2eproto_getter, &descriptor_table_common_2fpb_5fmsg_2fai_5fbone_2eproto_once,
      file_level_metadata_common_2fpb_5fmsg_2fai_5fbone_2eproto[0]);
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace pb_msg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
#include "google/protobuf/port_undef.inc"
