// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/pb_msg/ai_bone.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_common_2fpb_5fmsg_2fai_5fbone_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_common_2fpb_5fmsg_2fai_5fbone_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4024000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4024000 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "common/pb_msg/common.pb.h"
#include "common/pb_msg/ai_vertex_weight.pb.h"
#include "common/pb_msg/ai_node.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_common_2fpb_5fmsg_2fai_5fbone_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_common_2fpb_5fmsg_2fai_5fbone_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_common_2fpb_5fmsg_2fai_5fbone_2eproto;
namespace pb_msg {
class AiBone;
struct AiBoneDefaultTypeInternal;
extern AiBoneDefaultTypeInternal _AiBone_default_instance_;
}  // namespace pb_msg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace pb_msg {

// ===================================================================


// -------------------------------------------------------------------

class AiBone final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb_msg.AiBone) */ {
 public:
  inline AiBone() : AiBone(nullptr) {}
  ~AiBone() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR AiBone(::google::protobuf::internal::ConstantInitialized);

  AiBone(const AiBone& from);
  AiBone(AiBone&& from) noexcept
    : AiBone() {
    *this = ::std::move(from);
  }

  inline AiBone& operator=(const AiBone& from) {
    CopyFrom(from);
    return *this;
  }
  inline AiBone& operator=(AiBone&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AiBone& default_instance() {
    return *internal_default_instance();
  }
  static inline const AiBone* internal_default_instance() {
    return reinterpret_cast<const AiBone*>(
               &_AiBone_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AiBone& a, AiBone& b) {
    a.Swap(&b);
  }
  inline void Swap(AiBone* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AiBone* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AiBone* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AiBone>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AiBone& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const AiBone& from) {
    AiBone::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AiBone* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "pb_msg.AiBone";
  }
  protected:
  explicit AiBone(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kArmatureFieldNumber = 3,
    kNodeFieldNumber = 4,
    kWeightsFieldNumber = 5,
    kNameFieldNumber = 1,
    kOffsetMatrixFieldNumber = 6,
    kNumWeightsFieldNumber = 2,
  };
  // repeated .pb_msg.AiNode Armature = 3;
  int armature_size() const;
  private:
  int _internal_armature_size() const;

  public:
  void clear_armature() ;
  ::pb_msg::AiNode* mutable_armature(int index);
  ::google::protobuf::RepeatedPtrField< ::pb_msg::AiNode >*
      mutable_armature();
  private:
  const ::google::protobuf::RepeatedPtrField<::pb_msg::AiNode>& _internal_armature() const;
  ::google::protobuf::RepeatedPtrField<::pb_msg::AiNode>* _internal_mutable_armature();
  public:
  const ::pb_msg::AiNode& armature(int index) const;
  ::pb_msg::AiNode* add_armature();
  const ::google::protobuf::RepeatedPtrField< ::pb_msg::AiNode >&
      armature() const;
  // repeated .pb_msg.AiNode Node = 4;
  int node_size() const;
  private:
  int _internal_node_size() const;

  public:
  void clear_node() ;
  ::pb_msg::AiNode* mutable_node(int index);
  ::google::protobuf::RepeatedPtrField< ::pb_msg::AiNode >*
      mutable_node();
  private:
  const ::google::protobuf::RepeatedPtrField<::pb_msg::AiNode>& _internal_node() const;
  ::google::protobuf::RepeatedPtrField<::pb_msg::AiNode>* _internal_mutable_node();
  public:
  const ::pb_msg::AiNode& node(int index) const;
  ::pb_msg::AiNode* add_node();
  const ::google::protobuf::RepeatedPtrField< ::pb_msg::AiNode >&
      node() const;
  // repeated .pb_msg.AiVertexWeight Weights = 5;
  int weights_size() const;
  private:
  int _internal_weights_size() const;

  public:
  void clear_weights() ;
  ::pb_msg::AiVertexWeight* mutable_weights(int index);
  ::google::protobuf::RepeatedPtrField< ::pb_msg::AiVertexWeight >*
      mutable_weights();
  private:
  const ::google::protobuf::RepeatedPtrField<::pb_msg::AiVertexWeight>& _internal_weights() const;
  ::google::protobuf::RepeatedPtrField<::pb_msg::AiVertexWeight>* _internal_mutable_weights();
  public:
  const ::pb_msg::AiVertexWeight& weights(int index) const;
  ::pb_msg::AiVertexWeight* add_weights();
  const ::google::protobuf::RepeatedPtrField< ::pb_msg::AiVertexWeight >&
      weights() const;
  // string Name = 1;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* ptr);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // .pb_msg.AiMatrix4x4 OffsetMatrix = 6;
  bool has_offsetmatrix() const;
  void clear_offsetmatrix() ;
  const ::pb_msg::AiMatrix4x4& offsetmatrix() const;
  PROTOBUF_NODISCARD ::pb_msg::AiMatrix4x4* release_offsetmatrix();
  ::pb_msg::AiMatrix4x4* mutable_offsetmatrix();
  void set_allocated_offsetmatrix(::pb_msg::AiMatrix4x4* value);
  void unsafe_arena_set_allocated_offsetmatrix(::pb_msg::AiMatrix4x4* value);
  ::pb_msg::AiMatrix4x4* unsafe_arena_release_offsetmatrix();

  private:
  const ::pb_msg::AiMatrix4x4& _internal_offsetmatrix() const;
  ::pb_msg::AiMatrix4x4* _internal_mutable_offsetmatrix();

  public:
  // uint32 NumWeights = 2;
  void clear_numweights() ;
  ::uint32_t numweights() const;
  void set_numweights(::uint32_t value);

  private:
  ::uint32_t _internal_numweights() const;
  void _internal_set_numweights(::uint32_t value);

  public:
  // @@protoc_insertion_point(class_scope:pb_msg.AiBone)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 6, 4, 26, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::pb_msg::AiNode > armature_;
    ::google::protobuf::RepeatedPtrField< ::pb_msg::AiNode > node_;
    ::google::protobuf::RepeatedPtrField< ::pb_msg::AiVertexWeight > weights_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::pb_msg::AiMatrix4x4* offsetmatrix_;
    ::uint32_t numweights_;
    PROTOBUF_TSAN_DECLARE_MEMBER;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_common_2fpb_5fmsg_2fai_5fbone_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AiBone

// string Name = 1;
inline void AiBone::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& AiBone::name() const {
  // @@protoc_insertion_point(field_get:pb_msg.AiBone.Name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void AiBone::set_name(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:pb_msg.AiBone.Name)
}
inline std::string* AiBone::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:pb_msg.AiBone.Name)
  return _s;
}
inline const std::string& AiBone::_internal_name() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.name_.Get();
}
inline void AiBone::_internal_set_name(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* AiBone::_internal_mutable_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.name_.Mutable( GetArenaForAllocation());
}
inline std::string* AiBone::release_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:pb_msg.AiBone.Name)
  return _impl_.name_.Release();
}
inline void AiBone::set_allocated_name(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.name_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.name_.IsDefault()) {
          _impl_.name_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:pb_msg.AiBone.Name)
}

// uint32 NumWeights = 2;
inline void AiBone::clear_numweights() {
  _impl_.numweights_ = 0u;
}
inline ::uint32_t AiBone::numweights() const {
  // @@protoc_insertion_point(field_get:pb_msg.AiBone.NumWeights)
  return _internal_numweights();
}
inline void AiBone::set_numweights(::uint32_t value) {
  _internal_set_numweights(value);
  // @@protoc_insertion_point(field_set:pb_msg.AiBone.NumWeights)
}
inline ::uint32_t AiBone::_internal_numweights() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.numweights_;
}
inline void AiBone::_internal_set_numweights(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.numweights_ = value;
}

// repeated .pb_msg.AiNode Armature = 3;
inline int AiBone::_internal_armature_size() const {
  return _internal_armature().size();
}
inline int AiBone::armature_size() const {
  return _internal_armature_size();
}
inline ::pb_msg::AiNode* AiBone::mutable_armature(int index) {
  // @@protoc_insertion_point(field_mutable:pb_msg.AiBone.Armature)
  return _internal_mutable_armature()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::pb_msg::AiNode >*
AiBone::mutable_armature() {
  // @@protoc_insertion_point(field_mutable_list:pb_msg.AiBone.Armature)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_armature();
}
inline const ::pb_msg::AiNode& AiBone::armature(int index) const {
  // @@protoc_insertion_point(field_get:pb_msg.AiBone.Armature)
    return _internal_armature().Get(index);
}
inline ::pb_msg::AiNode* AiBone::add_armature() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::pb_msg::AiNode* _add = _internal_mutable_armature()->Add();
  // @@protoc_insertion_point(field_add:pb_msg.AiBone.Armature)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField< ::pb_msg::AiNode >&
AiBone::armature() const {
  // @@protoc_insertion_point(field_list:pb_msg.AiBone.Armature)
  return _internal_armature();
}
inline const ::google::protobuf::RepeatedPtrField<::pb_msg::AiNode>&
AiBone::_internal_armature() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.armature_;
}
inline ::google::protobuf::RepeatedPtrField<::pb_msg::AiNode>*
AiBone::_internal_mutable_armature() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.armature_;
}

// repeated .pb_msg.AiNode Node = 4;
inline int AiBone::_internal_node_size() const {
  return _internal_node().size();
}
inline int AiBone::node_size() const {
  return _internal_node_size();
}
inline ::pb_msg::AiNode* AiBone::mutable_node(int index) {
  // @@protoc_insertion_point(field_mutable:pb_msg.AiBone.Node)
  return _internal_mutable_node()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::pb_msg::AiNode >*
AiBone::mutable_node() {
  // @@protoc_insertion_point(field_mutable_list:pb_msg.AiBone.Node)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_node();
}
inline const ::pb_msg::AiNode& AiBone::node(int index) const {
  // @@protoc_insertion_point(field_get:pb_msg.AiBone.Node)
    return _internal_node().Get(index);
}
inline ::pb_msg::AiNode* AiBone::add_node() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::pb_msg::AiNode* _add = _internal_mutable_node()->Add();
  // @@protoc_insertion_point(field_add:pb_msg.AiBone.Node)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField< ::pb_msg::AiNode >&
AiBone::node() const {
  // @@protoc_insertion_point(field_list:pb_msg.AiBone.Node)
  return _internal_node();
}
inline const ::google::protobuf::RepeatedPtrField<::pb_msg::AiNode>&
AiBone::_internal_node() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.node_;
}
inline ::google::protobuf::RepeatedPtrField<::pb_msg::AiNode>*
AiBone::_internal_mutable_node() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.node_;
}

// repeated .pb_msg.AiVertexWeight Weights = 5;
inline int AiBone::_internal_weights_size() const {
  return _internal_weights().size();
}
inline int AiBone::weights_size() const {
  return _internal_weights_size();
}
inline ::pb_msg::AiVertexWeight* AiBone::mutable_weights(int index) {
  // @@protoc_insertion_point(field_mutable:pb_msg.AiBone.Weights)
  return _internal_mutable_weights()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::pb_msg::AiVertexWeight >*
AiBone::mutable_weights() {
  // @@protoc_insertion_point(field_mutable_list:pb_msg.AiBone.Weights)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_weights();
}
inline const ::pb_msg::AiVertexWeight& AiBone::weights(int index) const {
  // @@protoc_insertion_point(field_get:pb_msg.AiBone.Weights)
    return _internal_weights().Get(index);
}
inline ::pb_msg::AiVertexWeight* AiBone::add_weights() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::pb_msg::AiVertexWeight* _add = _internal_mutable_weights()->Add();
  // @@protoc_insertion_point(field_add:pb_msg.AiBone.Weights)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField< ::pb_msg::AiVertexWeight >&
AiBone::weights() const {
  // @@protoc_insertion_point(field_list:pb_msg.AiBone.Weights)
  return _internal_weights();
}
inline const ::google::protobuf::RepeatedPtrField<::pb_msg::AiVertexWeight>&
AiBone::_internal_weights() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.weights_;
}
inline ::google::protobuf::RepeatedPtrField<::pb_msg::AiVertexWeight>*
AiBone::_internal_mutable_weights() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.weights_;
}

// .pb_msg.AiMatrix4x4 OffsetMatrix = 6;
inline bool AiBone::has_offsetmatrix() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.offsetmatrix_ != nullptr);
  return value;
}
inline const ::pb_msg::AiMatrix4x4& AiBone::_internal_offsetmatrix() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::pb_msg::AiMatrix4x4* p = _impl_.offsetmatrix_;
  return p != nullptr ? *p : reinterpret_cast<const ::pb_msg::AiMatrix4x4&>(::pb_msg::_AiMatrix4x4_default_instance_);
}
inline const ::pb_msg::AiMatrix4x4& AiBone::offsetmatrix() const {
  // @@protoc_insertion_point(field_get:pb_msg.AiBone.OffsetMatrix)
  return _internal_offsetmatrix();
}
inline void AiBone::unsafe_arena_set_allocated_offsetmatrix(::pb_msg::AiMatrix4x4* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.offsetmatrix_);
  }
  _impl_.offsetmatrix_ = reinterpret_cast<::pb_msg::AiMatrix4x4*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:pb_msg.AiBone.OffsetMatrix)
}
inline ::pb_msg::AiMatrix4x4* AiBone::release_offsetmatrix() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::pb_msg::AiMatrix4x4* released = _impl_.offsetmatrix_;
  _impl_.offsetmatrix_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::pb_msg::AiMatrix4x4* AiBone::unsafe_arena_release_offsetmatrix() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:pb_msg.AiBone.OffsetMatrix)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::pb_msg::AiMatrix4x4* temp = _impl_.offsetmatrix_;
  _impl_.offsetmatrix_ = nullptr;
  return temp;
}
inline ::pb_msg::AiMatrix4x4* AiBone::_internal_mutable_offsetmatrix() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.offsetmatrix_ == nullptr) {
    auto* p = CreateMaybeMessage<::pb_msg::AiMatrix4x4>(GetArenaForAllocation());
    _impl_.offsetmatrix_ = reinterpret_cast<::pb_msg::AiMatrix4x4*>(p);
  }
  return _impl_.offsetmatrix_;
}
inline ::pb_msg::AiMatrix4x4* AiBone::mutable_offsetmatrix() {
  ::pb_msg::AiMatrix4x4* _msg = _internal_mutable_offsetmatrix();
  // @@protoc_insertion_point(field_mutable:pb_msg.AiBone.OffsetMatrix)
  return _msg;
}
inline void AiBone::set_allocated_offsetmatrix(::pb_msg::AiMatrix4x4* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.offsetmatrix_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::google::protobuf::MessageLite*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.offsetmatrix_ = reinterpret_cast<::pb_msg::AiMatrix4x4*>(value);
  // @@protoc_insertion_point(field_set_allocated:pb_msg.AiBone.OffsetMatrix)
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace pb_msg


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_common_2fpb_5fmsg_2fai_5fbone_2eproto_2epb_2eh
