// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: common/pb_msg/ai_vertex_weight.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_common_2fpb_5fmsg_2fai_5fvertex_5fweight_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_common_2fpb_5fmsg_2fai_5fvertex_5fweight_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4024000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4024000 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_common_2fpb_5fmsg_2fai_5fvertex_5fweight_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_common_2fpb_5fmsg_2fai_5fvertex_5fweight_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_common_2fpb_5fmsg_2fai_5fvertex_5fweight_2eproto;
namespace pb_msg {
class AiVertexWeight;
struct AiVertexWeightDefaultTypeInternal;
extern AiVertexWeightDefaultTypeInternal _AiVertexWeight_default_instance_;
}  // namespace pb_msg
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace pb_msg {

// ===================================================================


// -------------------------------------------------------------------

class AiVertexWeight final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:pb_msg.AiVertexWeight) */ {
 public:
  inline AiVertexWeight() : AiVertexWeight(nullptr) {}
  ~AiVertexWeight() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR AiVertexWeight(::google::protobuf::internal::ConstantInitialized);

  AiVertexWeight(const AiVertexWeight& from);
  AiVertexWeight(AiVertexWeight&& from) noexcept
    : AiVertexWeight() {
    *this = ::std::move(from);
  }

  inline AiVertexWeight& operator=(const AiVertexWeight& from) {
    CopyFrom(from);
    return *this;
  }
  inline AiVertexWeight& operator=(AiVertexWeight&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const AiVertexWeight& default_instance() {
    return *internal_default_instance();
  }
  static inline const AiVertexWeight* internal_default_instance() {
    return reinterpret_cast<const AiVertexWeight*>(
               &_AiVertexWeight_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(AiVertexWeight& a, AiVertexWeight& b) {
    a.Swap(&b);
  }
  inline void Swap(AiVertexWeight* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(AiVertexWeight* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  AiVertexWeight* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<AiVertexWeight>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const AiVertexWeight& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const AiVertexWeight& from) {
    AiVertexWeight::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(AiVertexWeight* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "pb_msg.AiVertexWeight";
  }
  protected:
  explicit AiVertexWeight(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kVertexIdFieldNumber = 1,
    kWeightFieldNumber = 2,
  };
  // uint32 VertexId = 1;
  void clear_vertexid() ;
  ::uint32_t vertexid() const;
  void set_vertexid(::uint32_t value);

  private:
  ::uint32_t _internal_vertexid() const;
  void _internal_set_vertexid(::uint32_t value);

  public:
  // float Weight = 2;
  void clear_weight() ;
  float weight() const;
  void set_weight(float value);

  private:
  float _internal_weight() const;
  void _internal_set_weight(float value);

  public:
  // @@protoc_insertion_point(class_scope:pb_msg.AiVertexWeight)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2, 0, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::uint32_t vertexid_;
    float weight_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_common_2fpb_5fmsg_2fai_5fvertex_5fweight_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// AiVertexWeight

// uint32 VertexId = 1;
inline void AiVertexWeight::clear_vertexid() {
  _impl_.vertexid_ = 0u;
}
inline ::uint32_t AiVertexWeight::vertexid() const {
  // @@protoc_insertion_point(field_get:pb_msg.AiVertexWeight.VertexId)
  return _internal_vertexid();
}
inline void AiVertexWeight::set_vertexid(::uint32_t value) {
  _internal_set_vertexid(value);
  // @@protoc_insertion_point(field_set:pb_msg.AiVertexWeight.VertexId)
}
inline ::uint32_t AiVertexWeight::_internal_vertexid() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.vertexid_;
}
inline void AiVertexWeight::_internal_set_vertexid(::uint32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.vertexid_ = value;
}

// float Weight = 2;
inline void AiVertexWeight::clear_weight() {
  _impl_.weight_ = 0;
}
inline float AiVertexWeight::weight() const {
  // @@protoc_insertion_point(field_get:pb_msg.AiVertexWeight.Weight)
  return _internal_weight();
}
inline void AiVertexWeight::set_weight(float value) {
  _internal_set_weight(value);
  // @@protoc_insertion_point(field_set:pb_msg.AiVertexWeight.Weight)
}
inline float AiVertexWeight::_internal_weight() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.weight_;
}
inline void AiVertexWeight::_internal_set_weight(float value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.weight_ = value;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace pb_msg


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_common_2fpb_5fmsg_2fai_5fvertex_5fweight_2eproto_2epb_2eh
