// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: common/pb_msg/ai_vertex_weight.proto

package pb_msg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// * @brief A single influence of a bone on a vertex.
type AiVertexWeight struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// ! Index of the vertex which is influenced by the bone.
	VertexId uint32 `protobuf:"varint,1,opt,name=VertexId,proto3" json:"VertexId,omitempty"`
	// ! The strength of the influence in the range (0...1).
	// ! The influence from all bones at one vertex amounts to 1.
	Weight float32 `protobuf:"fixed32,2,opt,name=Weight,proto3" json:"Weight,omitempty"`
}

func (x *AiVertexWeight) Reset() {
	*x = AiVertexWeight{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_pb_msg_ai_vertex_weight_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AiVertexWeight) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AiVertexWeight) ProtoMessage() {}

func (x *AiVertexWeight) ProtoReflect() protoreflect.Message {
	mi := &file_common_pb_msg_ai_vertex_weight_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AiVertexWeight.ProtoReflect.Descriptor instead.
func (*AiVertexWeight) Descriptor() ([]byte, []int) {
	return file_common_pb_msg_ai_vertex_weight_proto_rawDescGZIP(), []int{0}
}

func (x *AiVertexWeight) GetVertexId() uint32 {
	if x != nil {
		return x.VertexId
	}
	return 0
}

func (x *AiVertexWeight) GetWeight() float32 {
	if x != nil {
		return x.Weight
	}
	return 0
}

var File_common_pb_msg_ai_vertex_weight_proto protoreflect.FileDescriptor

var file_common_pb_msg_ai_vertex_weight_proto_rawDesc = []byte{
	0x0a, 0x24, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x2f,
	0x61, 0x69, 0x5f, 0x76, 0x65, 0x72, 0x74, 0x65, 0x78, 0x5f, 0x77, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x70, 0x62, 0x5f, 0x6d, 0x73, 0x67, 0x22, 0x44,
	0x0a, 0x0e, 0x41, 0x69, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x57, 0x65, 0x69, 0x67, 0x68, 0x74,
	0x12, 0x1a, 0x0a, 0x08, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x08, 0x56, 0x65, 0x72, 0x74, 0x65, 0x78, 0x49, 0x64, 0x12, 0x16, 0x0a, 0x06,
	0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x02, 0x52, 0x06, 0x57, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x42, 0x0f, 0x5a, 0x0d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x70,
	0x62, 0x5f, 0x6d, 0x73, 0x67, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_common_pb_msg_ai_vertex_weight_proto_rawDescOnce sync.Once
	file_common_pb_msg_ai_vertex_weight_proto_rawDescData = file_common_pb_msg_ai_vertex_weight_proto_rawDesc
)

func file_common_pb_msg_ai_vertex_weight_proto_rawDescGZIP() []byte {
	file_common_pb_msg_ai_vertex_weight_proto_rawDescOnce.Do(func() {
		file_common_pb_msg_ai_vertex_weight_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_pb_msg_ai_vertex_weight_proto_rawDescData)
	})
	return file_common_pb_msg_ai_vertex_weight_proto_rawDescData
}

var file_common_pb_msg_ai_vertex_weight_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_pb_msg_ai_vertex_weight_proto_goTypes = []interface{}{
	(*AiVertexWeight)(nil), // 0: pb_msg.AiVertexWeight
}
var file_common_pb_msg_ai_vertex_weight_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_pb_msg_ai_vertex_weight_proto_init() }
func file_common_pb_msg_ai_vertex_weight_proto_init() {
	if File_common_pb_msg_ai_vertex_weight_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_pb_msg_ai_vertex_weight_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AiVertexWeight); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_pb_msg_ai_vertex_weight_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_pb_msg_ai_vertex_weight_proto_goTypes,
		DependencyIndexes: file_common_pb_msg_ai_vertex_weight_proto_depIdxs,
		MessageInfos:      file_common_pb_msg_ai_vertex_weight_proto_msgTypes,
	}.Build()
	File_common_pb_msg_ai_vertex_weight_proto = out.File
	file_common_pb_msg_ai_vertex_weight_proto_rawDesc = nil
	file_common_pb_msg_ai_vertex_weight_proto_goTypes = nil
	file_common_pb_msg_ai_vertex_weight_proto_depIdxs = nil
}
